//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekU.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeekU.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$type&quot;:&quot;System.Collections.Generic.List`1[[SeekU.Eventing.DomainEvent, SeekU]], mscorlib&quot;,&quot;$values&quot;:[{&quot;$type&quot;:&quot;SampleDomain.Events.AccountDebitedEvent, SampleDomain&quot;,&quot;Id&quot;:&quot;ce533f1d-56db-493a-9838-a2b801427761&quot;,&quot;Amount&quot;:50.0,&quot;Sequence&quot;:2,&quot;EventDate&quot;:&quot;2014-01-20T02:34:53.2997746Z&quot;}]}.
        /// </summary>
        internal static string JsonSerializedDebitEvent {
            get {
                return ResourceManager.GetString("JsonSerializedDebitEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$type&quot;:&quot;System.Collections.Generic.List`1[[SeekU.Eventing.DomainEvent, SeekU]], mscorlib&quot;,&quot;$values&quot;:[{&quot;$type&quot;:&quot;SampleDomain.Events.AccountCreatedEvent, SampleDomain&quot;,&quot;Id&quot;:&quot;c1fb0691-9aaa-4f06-9d34-a2b80141c05f&quot;,&quot;Amount&quot;:950.0,&quot;Sequence&quot;:1,&quot;EventDate&quot;:&quot;2014-01-20T02:31:27.6869581Z&quot;}]}.
        /// </summary>
        internal static string JsonSerializedNewAccountEvent {
            get {
                return ResourceManager.GetString("JsonSerializedNewAccountEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$type&quot;:&quot;SampleDomain.Domain.BankAccountSnapshot, SampleDomain&quot;,&quot;Balance&quot;:900.0}.
        /// </summary>
        internal static string JsonSerializedSnapshot {
            get {
                return ResourceManager.GetString("JsonSerializedSnapshot", resourceCulture);
            }
        }
    }
}
